// Direct cancellation page URLs for known services.
// All URLs open to the subscription/billing management page where the user can cancel.
const CANCEL_URL_MAP: Record<string, string> = {
  // Streaming video
  "netflix": "https://www.netflix.com/cancelplan",
  "hulu": "https://secure.hulu.com/account/cancel",
  "disney+": "https://www.disneyplus.com/account/subscription",
  "disney plus": "https://www.disneyplus.com/account/subscription",
  "amazon prime": "https://www.amazon.com/mc/pipelines/cancellation",
  "amazon prime video": "https://www.amazon.com/mc/pipelines/cancellation",
  "prime video": "https://www.amazon.com/mc/pipelines/cancellation",
  "hbo": "https://www.max.com/settings/subscription",
  "hbo max": "https://www.max.com/settings/subscription",
  "max": "https://www.max.com/settings/subscription",
  "apple tv+": "https://appleid.apple.com/account/manage",
  "apple tv plus": "https://appleid.apple.com/account/manage",
  "peacock": "https://www.peacocktv.com/account/plan",
  "paramount+": "https://www.paramountplus.com/account/",
  "paramount plus": "https://www.paramountplus.com/account/",
  "youtube premium": "https://www.youtube.com/paid_memberships",
  "youtube tv": "https://tv.youtube.com/settings/membership",
  "crunchyroll": "https://www.crunchyroll.com/acct/membership",
  "twitch": "https://www.twitch.tv/settings/subscriptions",
  "discovery+": "https://www.discoveryplus.com/manage",
  "discovery plus": "https://www.discoveryplus.com/manage",
  "espn+": "https://secure.espn.com/espnplus/member",
  "espn plus": "https://secure.espn.com/espnplus/member",
  "mubi": "https://mubi.com/settings/membership",
  "shudder": "https://www.shudder.com/account",
  "plex": "https://www.plex.tv/plex-pass/",

  // Music
  "spotify": "https://www.spotify.com/account/subscription/cancel/",
  "apple music": "https://appleid.apple.com/account/manage",
  "tidal": "https://account.tidal.com/subscription",
  "soundcloud": "https://soundcloud.com/settings/subscription",
  "pandora": "https://www.pandora.com/account/premium",
  "deezer": "https://www.deezer.com/account/subscription",
  "amazon music": "https://music.amazon.com/settings",
  "audible": "https://www.audible.com/account/cancel-membership",
  "kindle unlimited": "https://www.amazon.com/kindle-dbs/ku/manage",

  // Productivity & SaaS
  "microsoft 365": "https://account.microsoft.com/services",
  "office 365": "https://account.microsoft.com/services",
  "microsoft office": "https://account.microsoft.com/services",
  "google workspace": "https://admin.google.com/ac/billing/subscriptions",
  "google one": "https://one.google.com/settings",
  "dropbox": "https://www.dropbox.com/account/plan",
  "notion": "https://www.notion.so/settings-workspace/billing",
  "slack": "https://app.slack.com/billing/settings",
  "zoom": "https://zoom.us/billing",
  "github": "https://github.com/settings/billing",
  "github copilot": "https://github.com/settings/copilot",
  "gitlab": "https://gitlab.com/-/profile/billing",
  "adobe": "https://account.adobe.com/plans",
  "adobe creative cloud": "https://account.adobe.com/plans",
  "adobe acrobat": "https://account.adobe.com/plans",
  "adobe acrobat pro": "https://account.adobe.com/plans",
  "adobe acrobat reader": "https://account.adobe.com/plans",
  "adobe photoshop": "https://account.adobe.com/plans",
  "adobe illustrator": "https://account.adobe.com/plans",
  "adobe premiere": "https://account.adobe.com/plans",
  "figma": "https://www.figma.com/settings/billing",
  "linear": "https://linear.app/settings/billing",
  "jira": "https://admin.atlassian.com/billing",
  "confluence": "https://admin.atlassian.com/billing",
  "atlassian": "https://admin.atlassian.com/billing",
  "trello": "https://trello.com/billing",
  "asana": "https://app.asana.com/admin/billing",
  "monday": "https://[your-account].monday.com/admin/billing",
  "monday.com": "https://[your-account].monday.com/admin/billing",
  "clickup": "https://app.clickup.com/settings/billing",
  "airtable": "https://airtable.com/account",
  "webflow": "https://webflow.com/dashboard/account/billing",
  "squarespace": "https://account.squarespace.com/billing",
  "shopify": "https://admin.shopify.com/store/[your-store]/settings/billing",
  "mailchimp": "https://admin.mailchimp.com/account/billing-history/",
  "canva": "https://www.canva.com/settings/billing",
  "grammarly": "https://account.grammarly.com/subscription",

  // Security & Privacy
  "1password": "https://my.1password.com/profile/billing",
  "lastpass": "https://lastpass.com/pay/buy.php?tab=billing",
  "dashlane": "https://app.dashlane.com/settings/plan",
  "bitwarden": "https://vault.bitwarden.com/#/settings/subscription",
  "nordvpn": "https://my.nordaccount.com/plans/",
  "expressvpn": "https://www.expressvpn.com/subscriptions",
  "surfshark": "https://my.surfshark.com/vpn/manual",
  "proton": "https://account.proton.me/dashboard",
  "protonmail": "https://account.proton.me/dashboard",
  "proton vpn": "https://account.proton.me/dashboard",
  "protonvpn": "https://account.proton.me/dashboard",

  // AI & Dev tools
  "chatgpt": "https://chat.openai.com/settings/billing",
  "openai": "https://platform.openai.com/account/billing",
  "vercel": "https://vercel.com/account/billing",
  "netlify": "https://app.netlify.com/account/billing",
  "digitalocean": "https://cloud.digitalocean.com/account/billing",
  "cloudflare": "https://dash.cloudflare.com/profile/billing",
  "datadog": "https://app.datadoghq.com/account/billing",

  // Food & delivery
  "hellofresh": "https://www.hellofresh.com/my-account/subscription",
  "hello fresh": "https://www.hellofresh.com/my-account/subscription",
  "factor": "https://www.factor75.com/plans/subscription",
  "factor 75": "https://www.factor75.com/plans/subscription",
  "green chef": "https://www.greenchef.com/account/subscription",
  "every plate": "https://www.everyplate.com/my-account/subscription",
  "everyplate": "https://www.everyplate.com/my-account/subscription",
  "home chef": "https://www.homechef.com/my-account/subscription",
  "marley spoon": "https://marleyspoon.com/account/subscription",
  "sun basket": "https://sunbasket.com/account",

  // Fitness & wellness
  "peloton": "https://members.onepeloton.com/profile/membership",
  "noom": "https://web.noom.com/dashboard/subscription",
  "calm": "https://www.calm.com/settings/subscription",
  "headspace": "https://www.headspace.com/account/subscription",
  "strava": "https://www.strava.com/settings/subscription",
  "whoop": "https://app.whoop.com/profile/membership",

  // Gaming
  "xbox game pass": "https://account.microsoft.com/services",
  "xbox game pass ultimate": "https://account.microsoft.com/services",
  "xbox": "https://account.microsoft.com/services",
  "playstation": "https://www.playstation.com/en-us/playstation-store/cancel-auto-renew/",
  "playstation plus": "https://www.playstation.com/en-us/playstation-store/cancel-auto-renew/",
  "playstation now": "https://www.playstation.com/en-us/playstation-store/cancel-auto-renew/",
  "playstation network": "https://www.playstation.com/en-us/playstation-store/cancel-auto-renew/",
  "sony playstation": "https://www.playstation.com/en-us/playstation-store/cancel-auto-renew/",
  "ps plus": "https://www.playstation.com/en-us/playstation-store/cancel-auto-renew/",
  "ps now": "https://www.playstation.com/en-us/playstation-store/cancel-auto-renew/",
  "psn": "https://www.playstation.com/en-us/playstation-store/cancel-auto-renew/",
  "nintendo switch online": "https://accounts.nintendo.com/membership/",
  "nintendo": "https://accounts.nintendo.com/membership/",
  "ea play": "https://myaccount.ea.com/cp-ui/subscriptions/index",
  "steam": "https://store.steampowered.com/subscriptions/",
  "epic games": "https://www.epicgames.com/account/subscriptions",

  // Big tech / storage
  "amazon": "https://www.amazon.com/mc/pipelines/cancellation",
  "icloud": "https://appleid.apple.com/account/manage",
  "icloud+": "https://appleid.apple.com/account/manage",
  "apple one": "https://appleid.apple.com/account/manage",
  "onedrive": "https://account.microsoft.com/services",
  "backblaze": "https://secure.backblaze.com/account.htm",

  // Education
  "duolingo": "https://www.duolingo.com/settings/subscriptions",
  "duolingo plus": "https://www.duolingo.com/settings/subscriptions",
  "masterclass": "https://www.masterclass.com/account/settings",
  "skillshare": "https://www.skillshare.com/account/membership",
  "udemy": "https://www.udemy.com/dashboard/account-settings/payment/",
  "coursera": "https://www.coursera.org/account-profile",
  "pluralsight": "https://app.pluralsight.com/settings/account/billing",
  "linkedin learning": "https://www.linkedin.com/learning/settings/membership",
  "linkedin premium": "https://www.linkedin.com/settings/billing",
};

export function getCancelUrl(name: string): string | undefined {
  return CANCEL_URL_MAP[name.toLowerCase().trim()];
}
